theme: jekyll-theme-cayman
title: Open Payment Data Visualization By Apache Spark
description: Xinming WANG, Yufeng XING, Kris KNAPP, Chandan NAYAK
author: Xinming WANG, Yufeng XING, Kris KNAPP, Chandan NAYAK